/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Mat } from "./Mat";
export * as factories from "./factories";
export { Mat__factory } from "./factories/Mat__factory";
